theme: jekyll-theme-tactile
title: ZFSBootMenu
description: A boot loader to manage ZFS boot environments
show_downloads: true
github:
  is_project_page: false
  public: true
  tar_url: "https://get.zfsbootmenu.org/tar.gz"
  owner_url: "https://github.com/zbm-dev/zfsbootmenu/"
